using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Cn.Com.Sve.OA.Entities;

namespace Cn.Com.Sve.OA.Entities.Criteria {
    public partial class StudentCriteria {
    	
    	public int? page{ get; set; }
    	public int? pagesize{ get; set; }
    	public string sortname{ get; set; }
    	public string sortorder{ get; set; }
    	
    	public int? IdSrh { get; set;}
    	public int? IdFromSrh { get; set;}
    	public int? IdToSrh { get; set;}
    	public string NameSrh { get; set;}
    	public string PinYinSrh { get; set;}
    	public string GenderSrh { get; set;}
    	public Nullable<System.DateTime> BirthdaySrh { get; set;}
    	public Nullable<System.DateTime> BirthdayFromSrh { get; set;}
    	public Nullable<System.DateTime> BirthdayToSrh { get; set;}
    	public string EduLevelSrh { get; set;}
    	public Nullable<System.DateTime> GraduateDateSrh { get; set;}
    	public Nullable<System.DateTime> GraduateDateFromSrh { get; set;}
    	public Nullable<System.DateTime> GraduateDateToSrh { get; set;}
    	public Nullable<int> ScoreSrh { get; set;}
    	public Nullable<int> ScoreFromSrh { get; set;}
    	public Nullable<int> ScoreToSrh { get; set;}
    	public Nullable<int> GruduateSchoolIdSrh { get; set;}
    	public Nullable<int> GruduateSchoolIdFromSrh { get; set;}
    	public Nullable<int> GruduateSchoolIdToSrh { get; set;}
    	public string ProfessionSrh { get; set;}
    	public string IdCardNoSrh { get; set;}
    	public string HuKouTypeSrh { get; set;}
    	public string AddressSrh { get; set;}
    	public string PostcodeSrh { get; set;}
    	public string FeeSourceSrh { get; set;}
    	public Nullable<int> SmallInfoSourceIdSrh { get; set;}
    	public Nullable<int> SmallInfoSourceIdFromSrh { get; set;}
    	public Nullable<int> SmallInfoSourceIdToSrh { get; set;}
    	public string QQSrh { get; set;}
    	public string EmailSrh { get; set;}
    	public string MobileSrh { get; set;}
    	public string HomeTelephoneSrh { get; set;}
    	public string OfficeTelephoneSrh { get; set;}
    	public string MemberRelType1Srh { get; set;}
    	public string MemberName1Srh { get; set;}
    	public string MemberCompany1Srh { get; set;}
    	public string MemberPosition1Srh { get; set;}
    	public string MemberMobile1Srh { get; set;}
    	public string MemberRelType2Srh { get; set;}
    	public string MemberName2Srh { get; set;}
    	public string MemberCompany2Srh { get; set;}
    	public string MemberPosition2Srh { get; set;}
    	public string MemberMobile2Srh { get; set;}
    	public string MemberRelType3Srh { get; set;}
    	public string MemberName3Srh { get; set;}
    	public string MemberCompany3Srh { get; set;}
    	public string MemberPosition3Srh { get; set;}
    	public string MemberMobile3Srh { get; set;}
    	public string MemberRelType4Srh { get; set;}
    	public string MemberName4Srh { get; set;}
    	public string MemberCompany4Srh { get; set;}
    	public string MemberPosition4Srh { get; set;}
    	public string MemberMobile4Srh { get; set;}
    	public string WorkStateSrh { get; set;}
    	public string StudyDuration1Srh { get; set;}
    	public string StudySchool1Srh { get; set;}
    	public string StudyPosition1Srh { get; set;}
    	public string StudyDuration2Srh { get; set;}
    	public string StudySchool2Srh { get; set;}
    	public string StudyPosition2Srh { get; set;}
    	public string StudyDuration3Srh { get; set;}
    	public string StudySchool3Srh { get; set;}
    	public string StudyPosition3Srh { get; set;}
    	public string SoftwareExpSrh { get; set;}
    	public string ProgramExpSrh { get; set;}
    	public string NetworkExpSrh { get; set;}
    	public string RelCourseSrh { get; set;}
    	public Nullable<int> DistrictIdSrh { get; set;}
    	public Nullable<int> DistrictIdFromSrh { get; set;}
    	public Nullable<int> DistrictIdToSrh { get; set;}
    	public string IntentCitySrh { get; set;}
    	public Nullable<int> ClazzIdSrh { get; set;}
    	public Nullable<int> ClazzIdFromSrh { get; set;}
    	public Nullable<int> ClazzIdToSrh { get; set;}
    	public string StudentNoSrh { get; set;}
    	public Nullable<System.DateTime> InSchoolDateSrh { get; set;}
    	public Nullable<System.DateTime> InSchoolDateFromSrh { get; set;}
    	public Nullable<System.DateTime> InSchoolDateToSrh { get; set;}
    	public string IsDormSrh { get; set;}
    	public string DormNoSrh { get; set;}
    	public string GiveCoursewareSrh { get; set;}
    	public string ConsultantsSrh { get; set;}
    	public string RemarkSrh { get; set;}
    	public System.DateTime? CreateTimeSrh { get; set;}
    	public System.DateTime? CreateTimeFromSrh { get; set;}
    	public System.DateTime? CreateTimeToSrh { get; set;}
    	public System.DateTime? LastUpdateTimeSrh { get; set;}
    	public System.DateTime? LastUpdateTimeFromSrh { get; set;}
    	public System.DateTime? LastUpdateTimeToSrh { get; set;}
    	public string IsGetQualificationSrh { get; set;}
    	public string StatusSrh { get; set;}
    	public string TechnicalWaySrh { get; set;}
    	public string NeedObtainWorkSrh { get; set;}
    	public string IntentPositionSrh { get; set;}
    	public Nullable<decimal> TargetSalarySrh { get; set;}
    	public Nullable<decimal> TargetSalaryFromSrh { get; set;}
    	public Nullable<decimal> TargetSalaryToSrh { get; set;}
    	public Nullable<System.DateTime> InsuranceStartDateSrh { get; set;}
    	public Nullable<System.DateTime> InsuranceStartDateFromSrh { get; set;}
    	public Nullable<System.DateTime> InsuranceStartDateToSrh { get; set;}
    	public Nullable<System.DateTime> InsuranceEndDateSrh { get; set;}
    	public Nullable<System.DateTime> InsuranceEndDateFromSrh { get; set;}
    	public Nullable<System.DateTime> InsuranceEndDateToSrh { get; set;}
    	public string GaoKaoBatchSrh { get; set;}
    	public string GiveNotebookSrh { get; set;}
    	public Nullable<decimal> MaxSalarySrh { get; set;}
    	public Nullable<decimal> MaxSalaryFromSrh { get; set;}
    	public Nullable<decimal> MaxSalaryToSrh { get; set;}
    	public Nullable<decimal> CurrentSalarySrh { get; set;}
    	public Nullable<decimal> CurrentSalaryFromSrh { get; set;}
    	public Nullable<decimal> CurrentSalaryToSrh { get; set;}
    	public Nullable<decimal> FirstSalarySrh { get; set;}
    	public Nullable<decimal> FirstSalaryFromSrh { get; set;}
    	public Nullable<decimal> FirstSalaryToSrh { get; set;}
    	public Nullable<System.DateTime> BeginSchoolTimeSrh { get; set;}
    	public Nullable<System.DateTime> BeginSchoolTimeFromSrh { get; set;}
    	public Nullable<System.DateTime> BeginSchoolTimeToSrh { get; set;}
    	public string MasterName1Srh { get; set;}
    	public string MasterName2Srh { get; set;}
    	public string MasterName3Srh { get; set;}
    	public string TeacherName1Srh { get; set;}
    	public string TeacherName2Srh { get; set;}
    	public string TeacherName3Srh { get; set;}
    	public Nullable<int> MasterId1Srh { get; set;}
    	public Nullable<int> MasterId1FromSrh { get; set;}
    	public Nullable<int> MasterId1ToSrh { get; set;}
    	public Nullable<int> MasterId2Srh { get; set;}
    	public Nullable<int> MasterId2FromSrh { get; set;}
    	public Nullable<int> MasterId2ToSrh { get; set;}
    	public Nullable<int> MasterId3Srh { get; set;}
    	public Nullable<int> MasterId3FromSrh { get; set;}
    	public Nullable<int> MasterId3ToSrh { get; set;}
    	public Nullable<int> TeacherId1Srh { get; set;}
    	public Nullable<int> TeacherId1FromSrh { get; set;}
    	public Nullable<int> TeacherId1ToSrh { get; set;}
    	public Nullable<int> TeacherId2Srh { get; set;}
    	public Nullable<int> TeacherId2FromSrh { get; set;}
    	public Nullable<int> TeacherId2ToSrh { get; set;}
    	public Nullable<int> TeacherId3Srh { get; set;}
    	public Nullable<int> TeacherId3FromSrh { get; set;}
    	public Nullable<int> TeacherId3ToSrh { get; set;}
    	public string QualificationSchoolSrh { get; set;}
    	public string InsuranceStatusSrh { get; set;}
    	public string OldOaIdSrh { get; set;}
    	public string OldOaInfoSourceSubTypeNameSrh { get; set;}
    	public string OldOaClassSrh { get; set;}
    	public string HasRelTeacherSrh { get; set;}
    	public string RelTeacherSrh { get; set;}
    	public string HomeIntroSrh { get; set;}
    	public string Give1Srh { get; set;}
    	public string Give2Srh { get; set;}
    	public string Give3Srh { get; set;}
    	public string Receive1Srh { get; set;}
    	public string Receive2Srh { get; set;}
    	public string Receive3Srh { get; set;}
    	public string Receive4Srh { get; set;}
    	public string Receive5Srh { get; set;}
    	public string Receive6Srh { get; set;}
    	public string Pic1Srh { get; set;}
    	public string Pic2Srh { get; set;}
    	public string Pic3Srh { get; set;}
    	public string Pic4Srh { get; set;}
    	public string Pic5Srh { get; set;}
    	public string Pic6Srh { get; set;}
    }
}
