//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class BigInfoSource
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<SmallInfoSource> SmallInfoSources
        {
            get
            {
                if (_smallInfoSources == null)
                {
                    var newCollection = new FixupCollection<SmallInfoSource>();
                    newCollection.CollectionChanged += FixupSmallInfoSources;
                    _smallInfoSources = newCollection;
                }
                return _smallInfoSources;
            }
            set
            {
                if (!ReferenceEquals(_smallInfoSources, value))
                {
                    var previousValue = _smallInfoSources as FixupCollection<SmallInfoSource>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSmallInfoSources;
                    }
                    _smallInfoSources = value;
                    var newValue = value as FixupCollection<SmallInfoSource>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSmallInfoSources;
                    }
                }
            }
        }
        private ICollection<SmallInfoSource> _smallInfoSources;

        #endregion

        #region Association Fixup
    
        private void FixupSmallInfoSources(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SmallInfoSource item in e.NewItems)
                {
                    item.BigInfoSource = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SmallInfoSource item in e.OldItems)
                {
                    if (ReferenceEquals(item.BigInfoSource, this))
                    {
                        item.BigInfoSource = null;
                    }
                }
            }
        }

        #endregion

    }
}
