//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class EmploymentStudentVisitLog
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int StudentId
        {
            get { return _studentId; }
            set
            {
                if (_studentId != value)
                {
                    if (Student != null && Student.Id != value)
                    {
                        Student = null;
                    }
                    _studentId = value;
                }
            }
        }
        private int _studentId;
    
        public virtual int VisitorId
        {
            get { return _visitorId; }
            set
            {
                if (_visitorId != value)
                {
                    if (Visitor != null && Visitor.Id != value)
                    {
                        Visitor = null;
                    }
                    _visitorId = value;
                }
            }
        }
        private int _visitorId;
    
        public virtual System.DateTime Time
        {
            get;
            set;
        }
    
        public virtual string Position
        {
            get;
            set;
        }
    
        public virtual string Objective
        {
            get;
            set;
        }
    
        public virtual string Content
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Student Student
        {
            get { return _student; }
            set
            {
                if (!ReferenceEquals(_student, value))
                {
                    var previousValue = _student;
                    _student = value;
                    FixupStudent(previousValue);
                }
            }
        }
        private Student _student;
    
        public virtual User Visitor
        {
            get { return _visitor; }
            set
            {
                if (!ReferenceEquals(_visitor, value))
                {
                    var previousValue = _visitor;
                    _visitor = value;
                    FixupVisitor(previousValue);
                }
            }
        }
        private User _visitor;

        #endregion

        #region Association Fixup
    
        private void FixupStudent(Student previousValue)
        {
            if (previousValue != null && previousValue.Employment_VisitLog.Contains(this))
            {
                previousValue.Employment_VisitLog.Remove(this);
            }
    
            if (Student != null)
            {
                if (!Student.Employment_VisitLog.Contains(this))
                {
                    Student.Employment_VisitLog.Add(this);
                }
                if (StudentId != Student.Id)
                {
                    StudentId = Student.Id;
                }
            }
        }
    
        private void FixupVisitor(User previousValue)
        {
            if (previousValue != null && previousValue.EmploymentStudentVisitLogs.Contains(this))
            {
                previousValue.EmploymentStudentVisitLogs.Remove(this);
            }
    
            if (Visitor != null)
            {
                if (!Visitor.EmploymentStudentVisitLogs.Contains(this))
                {
                    Visitor.EmploymentStudentVisitLogs.Add(this);
                }
                if (VisitorId != Visitor.Id)
                {
                    VisitorId = Visitor.Id;
                }
            }
        }

        #endregion

    }
}
