//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class EmploymentCompanyContactVisitLog
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int CompanyContactId
        {
            get { return _companyContactId; }
            set
            {
                if (_companyContactId != value)
                {
                    if (CompanyContact != null && CompanyContact.Id != value)
                    {
                        CompanyContact = null;
                    }
                    _companyContactId = value;
                }
            }
        }
        private int _companyContactId;
    
        public virtual System.DateTime Time
        {
            get;
            set;
        }
    
        public virtual int VisitorId
        {
            get { return _visitorId; }
            set
            {
                if (_visitorId != value)
                {
                    if (Visitor != null && Visitor.Id != value)
                    {
                        Visitor = null;
                    }
                    _visitorId = value;
                }
            }
        }
        private int _visitorId;
    
        public virtual string Type
        {
            get;
            set;
        }
    
        public virtual string Content
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual EmploymentCompanyContact CompanyContact
        {
            get { return _companyContact; }
            set
            {
                if (!ReferenceEquals(_companyContact, value))
                {
                    var previousValue = _companyContact;
                    _companyContact = value;
                    FixupCompanyContact(previousValue);
                }
            }
        }
        private EmploymentCompanyContact _companyContact;
    
        public virtual User Visitor
        {
            get { return _visitor; }
            set
            {
                if (!ReferenceEquals(_visitor, value))
                {
                    var previousValue = _visitor;
                    _visitor = value;
                    FixupVisitor(previousValue);
                }
            }
        }
        private User _visitor;

        #endregion

        #region Association Fixup
    
        private void FixupCompanyContact(EmploymentCompanyContact previousValue)
        {
            if (previousValue != null && previousValue.Employment_CompanyContact_VisitLog.Contains(this))
            {
                previousValue.Employment_CompanyContact_VisitLog.Remove(this);
            }
    
            if (CompanyContact != null)
            {
                if (!CompanyContact.Employment_CompanyContact_VisitLog.Contains(this))
                {
                    CompanyContact.Employment_CompanyContact_VisitLog.Add(this);
                }
                if (CompanyContactId != CompanyContact.Id)
                {
                    CompanyContactId = CompanyContact.Id;
                }
            }
        }
    
        private void FixupVisitor(User previousValue)
        {
            if (previousValue != null && previousValue.Employment_CompanyContact_VisitLog.Contains(this))
            {
                previousValue.Employment_CompanyContact_VisitLog.Remove(this);
            }
    
            if (Visitor != null)
            {
                if (!Visitor.Employment_CompanyContact_VisitLog.Contains(this))
                {
                    Visitor.Employment_CompanyContact_VisitLog.Add(this);
                }
                if (VisitorId != Visitor.Id)
                {
                    VisitorId = Visitor.Id;
                }
            }
        }

        #endregion

    }
}
