//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class EmploymentCompanyContact
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int CompanyId
        {
            get { return _companyId; }
            set
            {
                if (_companyId != value)
                {
                    if (Company != null && Company.Id != value)
                    {
                        Company = null;
                    }
                    _companyId = value;
                }
            }
        }
        private int _companyId;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Mobile
        {
            get;
            set;
        }
    
        public virtual string Position
        {
            get;
            set;
        }
    
        public virtual string Telephone
        {
            get;
            set;
        }
    
        public virtual string QQ
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string Introduction
        {
            get;
            set;
        }
    
        public virtual string OldOaId
        {
            get;
            set;
        }
    
        public virtual string OldOaCompanyId
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual EmploymentCompany Company
        {
            get { return _company; }
            set
            {
                if (!ReferenceEquals(_company, value))
                {
                    var previousValue = _company;
                    _company = value;
                    FixupCompany(previousValue);
                }
            }
        }
        private EmploymentCompany _company;

        #endregion

        #region Association Fixup
    
        private void FixupCompany(EmploymentCompany previousValue)
        {
            if (previousValue != null && previousValue.Contact.Contains(this))
            {
                previousValue.Contact.Remove(this);
            }
    
            if (Company != null)
            {
                if (!Company.Contact.Contains(this))
                {
                    Company.Contact.Add(this);
                }
                if (CompanyId != Company.Id)
                {
                    CompanyId = Company.Id;
                }
            }
        }

        #endregion

    }
}
