//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class ImportCustomer
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string ImportKey
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SchoolId
        {
            get;
            set;
        }
    
        public virtual string SchoolName
        {
            get;
            set;
        }
    
        public virtual string Level
        {
            get;
            set;
        }
    
        public virtual int MarketYear
        {
            get;
            set;
        }
    
        public virtual int InfoSource
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Gender
        {
            get;
            set;
        }
    
        public virtual string Tel
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ProvinceId
        {
            get;
            set;
        }
    
        public virtual string ProvinceName
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CityId
        {
            get;
            set;
        }
    
        public virtual string CityName
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DistrictId
        {
            get;
            set;
        }
    
        public virtual string DistrictName
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string Mobile
        {
            get;
            set;
        }
    
        public virtual string QQ
        {
            get;
            set;
        }
    
        public virtual string Clazz
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Score
        {
            get;
            set;
        }
    
        public virtual string Postcode
        {
            get;
            set;
        }
    
        public virtual string Contact
        {
            get;
            set;
        }
    
        public virtual string ImportType
        {
            get;
            set;
        }
    
        public virtual bool IsProcessed
        {
            get;
            set;
        }
    
        public virtual string ErrorMsg
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<ImportDupliate> ImportDupliates
        {
            get
            {
                if (_importDupliates == null)
                {
                    var newCollection = new FixupCollection<ImportDupliate>();
                    newCollection.CollectionChanged += FixupImportDupliates;
                    _importDupliates = newCollection;
                }
                return _importDupliates;
            }
            set
            {
                if (!ReferenceEquals(_importDupliates, value))
                {
                    var previousValue = _importDupliates as FixupCollection<ImportDupliate>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupImportDupliates;
                    }
                    _importDupliates = value;
                    var newValue = value as FixupCollection<ImportDupliate>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupImportDupliates;
                    }
                }
            }
        }
        private ICollection<ImportDupliate> _importDupliates;

        #endregion

        #region Association Fixup
    
        private void FixupImportDupliates(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ImportDupliate item in e.NewItems)
                {
                    item.ImportCustomer = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ImportDupliate item in e.OldItems)
                {
                    if (ReferenceEquals(item.ImportCustomer, this))
                    {
                        item.ImportCustomer = null;
                    }
                }
            }
        }

        #endregion

    }
}
