//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class QualificationStudent
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Clazz
        {
            get;
            set;
        }
    
        public virtual string TargetSchoolName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SignUpTime
        {
            get;
            set;
        }
    
        public virtual string SeqNo
        {
            get;
            set;
        }
    
        public virtual string TargetProfession
        {
            get;
            set;
        }
    
        public virtual string TargetLevel
        {
            get;
            set;
        }
    
        public virtual string StudentNo
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Sex
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Birthday
        {
            get;
            set;
        }
    
        public virtual string JiGuang
        {
            get;
            set;
        }
    
        public virtual string IdCardNo
        {
            get;
            set;
        }
    
        public virtual string MinZu
        {
            get;
            set;
        }
    
        public virtual string ZhengZhiMianMao
        {
            get;
            set;
        }
    
        public virtual string IsMarried
        {
            get;
            set;
        }
    
        public virtual string HomeAddress
        {
            get;
            set;
        }
    
        public virtual string HuKouAddress
        {
            get;
            set;
        }
    
        public virtual string CommAddress
        {
            get;
            set;
        }
    
        public virtual string Postcode
        {
            get;
            set;
        }
    
        public virtual string HomeTelephone
        {
            get;
            set;
        }
    
        public virtual string Mobile
        {
            get;
            set;
        }
    
        public virtual string QQ
        {
            get;
            set;
        }
    
        public virtual string Company
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string CompanyTelephoneNo
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> BeginWorkTime
        {
            get;
            set;
        }
    
        public virtual Nullable<int> WorkedYears
        {
            get;
            set;
        }
    
        public virtual string HighestEduLevel
        {
            get;
            set;
        }
    
        public virtual string HighestQualification
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> GraduateDate
        {
            get;
            set;
        }
    
        public virtual string GruduateSchool
        {
            get;
            set;
        }
    
        public virtual string HighestQualificationNo
        {
            get;
            set;
        }
    
        public virtual string StudyDuration1
        {
            get;
            set;
        }
    
        public virtual string StudySchool1
        {
            get;
            set;
        }
    
        public virtual string StudyPosition1
        {
            get;
            set;
        }
    
        public virtual string StudyDuration2
        {
            get;
            set;
        }
    
        public virtual string StudySchool2
        {
            get;
            set;
        }
    
        public virtual string StudyPosition2
        {
            get;
            set;
        }
    
        public virtual string StudyDuration3
        {
            get;
            set;
        }
    
        public virtual string StudySchool3
        {
            get;
            set;
        }
    
        public virtual string StudyPosition3
        {
            get;
            set;
        }
    
        public virtual string MemberRelType1
        {
            get;
            set;
        }
    
        public virtual string MemberName1
        {
            get;
            set;
        }
    
        public virtual string MemberMianMao1
        {
            get;
            set;
        }
    
        public virtual string MemberCompany1
        {
            get;
            set;
        }
    
        public virtual string MemberPosition1
        {
            get;
            set;
        }
    
        public virtual string MemberMobile1
        {
            get;
            set;
        }
    
        public virtual string MemberRelType2
        {
            get;
            set;
        }
    
        public virtual string MemberName2
        {
            get;
            set;
        }
    
        public virtual string MemberMianMao2
        {
            get;
            set;
        }
    
        public virtual string MemberCompany2
        {
            get;
            set;
        }
    
        public virtual string MemberPosition2
        {
            get;
            set;
        }
    
        public virtual string MemberMobile2
        {
            get;
            set;
        }
    
        public virtual string Remark
        {
            get;
            set;
        }
    
        public virtual string Status
        {
            get;
            set;
        }
    
        public virtual string Consultant
        {
            get;
            set;
        }
    
        public virtual string Referrer
        {
            get;
            set;
        }
    
        public virtual string ReferrerMobile
        {
            get;
            set;
        }
    
        public virtual string ReferrerQQ
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> MatriculateTime
        {
            get;
            set;
        }
    
        public virtual string NetUserName
        {
            get;
            set;
        }
    
        public virtual string NetPassword
        {
            get;
            set;
        }
    
        public virtual string StudyType
        {
            get;
            set;
        }
    
        public virtual string SubmitStatus
        {
            get;
            set;
        }
    
        public virtual string OfferStatus
        {
            get;
            set;
        }
    
        public virtual string PayStatus
        {
            get;
            set;
        }
    
        public virtual string PaperStatus
        {
            get;
            set;
        }
    
        public virtual string OldOAId
        {
            get;
            set;
        }
    
        public virtual string Photo1
        {
            get;
            set;
        }
    
        public virtual string Photo2
        {
            get;
            set;
        }
    
        public virtual string Photo3
        {
            get;
            set;
        }

        #endregion

    }
}
