//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class SchoolAd
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SchoolId
        {
            get { return _schoolId; }
            set
            {
                if (_schoolId != value)
                {
                    if (School != null && School.Id != value)
                    {
                        School = null;
                    }
                    _schoolId = value;
                }
            }
        }
        private int _schoolId;
    
        public virtual int Year
        {
            get;
            set;
        }
    
        public virtual Nullable<int> HighClassQty
        {
            get;
            set;
        }
    
        public virtual Nullable<int> HighStudentQty
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LowClassQty
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LowStudentQty
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DaoJiShiPai
        {
            get;
            set;
        }
    
        public virtual Nullable<int> JiaoShiBiaoYu
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ShuShiBiaoYu
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ShiTangBiaoYu
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LouTiBiaoYu
        {
            get;
            set;
        }
    
        public virtual Nullable<int> BuTiao
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TaiLi
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuaLi
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual School School
        {
            get { return _school; }
            set
            {
                if (!ReferenceEquals(_school, value))
                {
                    var previousValue = _school;
                    _school = value;
                    FixupSchool(previousValue);
                }
            }
        }
        private School _school;

        #endregion

        #region Association Fixup
    
        private void FixupSchool(School previousValue)
        {
            if (previousValue != null && previousValue.SchoolAds.Contains(this))
            {
                previousValue.SchoolAds.Remove(this);
            }
    
            if (School != null)
            {
                if (!School.SchoolAds.Contains(this))
                {
                    School.SchoolAds.Add(this);
                }
                if (SchoolId != School.Id)
                {
                    SchoolId = School.Id;
                }
            }
        }

        #endregion

    }
}
