//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class SchoolContact
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SchoolId
        {
            get { return _schoolId; }
            set
            {
                if (_schoolId != value)
                {
                    if (School != null && School.Id != value)
                    {
                        School = null;
                    }
                    _schoolId = value;
                }
            }
        }
        private int _schoolId;
    
        public virtual Nullable<int> Year
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Telephone
        {
            get;
            set;
        }
    
        public virtual string Mobile
        {
            get;
            set;
        }
    
        public virtual string QQ
        {
            get;
            set;
        }
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string Remark
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TopFlag
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OldOaId
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual School School
        {
            get { return _school; }
            set
            {
                if (!ReferenceEquals(_school, value))
                {
                    var previousValue = _school;
                    _school = value;
                    FixupSchool(previousValue);
                }
            }
        }
        private School _school;

        #endregion

        #region Association Fixup
    
        private void FixupSchool(School previousValue)
        {
            if (previousValue != null && previousValue.SchoolContacts.Contains(this))
            {
                previousValue.SchoolContacts.Remove(this);
            }
    
            if (School != null)
            {
                if (!School.SchoolContacts.Contains(this))
                {
                    School.SchoolContacts.Add(this);
                }
                if (SchoolId != School.Id)
                {
                    SchoolId = School.Id;
                }
            }
        }

        #endregion

    }
}
