//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class SmallInfoSource
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual int InfoSourceBigId
        {
            get { return _infoSourceBigId; }
            set
            {
                if (_infoSourceBigId != value)
                {
                    if (BigInfoSource != null && BigInfoSource.Id != value)
                    {
                        BigInfoSource = null;
                    }
                    _infoSourceBigId = value;
                }
            }
        }
        private int _infoSourceBigId;

        #endregion

        #region Navigation Properties
    
        public virtual BigInfoSource BigInfoSource
        {
            get { return _bigInfoSource; }
            set
            {
                if (!ReferenceEquals(_bigInfoSource, value))
                {
                    var previousValue = _bigInfoSource;
                    _bigInfoSource = value;
                    FixupBigInfoSource(previousValue);
                }
            }
        }
        private BigInfoSource _bigInfoSource;
    
        public virtual ICollection<Customer> Customers
        {
            get
            {
                if (_customers == null)
                {
                    var newCollection = new FixupCollection<Customer>();
                    newCollection.CollectionChanged += FixupCustomers;
                    _customers = newCollection;
                }
                return _customers;
            }
            set
            {
                if (!ReferenceEquals(_customers, value))
                {
                    var previousValue = _customers as FixupCollection<Customer>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCustomers;
                    }
                    _customers = value;
                    var newValue = value as FixupCollection<Customer>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCustomers;
                    }
                }
            }
        }
        private ICollection<Customer> _customers;
    
        public virtual ICollection<Student> Students
        {
            get
            {
                if (_students == null)
                {
                    var newCollection = new FixupCollection<Student>();
                    newCollection.CollectionChanged += FixupStudents;
                    _students = newCollection;
                }
                return _students;
            }
            set
            {
                if (!ReferenceEquals(_students, value))
                {
                    var previousValue = _students as FixupCollection<Student>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupStudents;
                    }
                    _students = value;
                    var newValue = value as FixupCollection<Student>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupStudents;
                    }
                }
            }
        }
        private ICollection<Student> _students;

        #endregion

        #region Association Fixup
    
        private void FixupBigInfoSource(BigInfoSource previousValue)
        {
            if (previousValue != null && previousValue.SmallInfoSources.Contains(this))
            {
                previousValue.SmallInfoSources.Remove(this);
            }
    
            if (BigInfoSource != null)
            {
                if (!BigInfoSource.SmallInfoSources.Contains(this))
                {
                    BigInfoSource.SmallInfoSources.Add(this);
                }
                if (InfoSourceBigId != BigInfoSource.Id)
                {
                    InfoSourceBigId = BigInfoSource.Id;
                }
            }
        }
    
        private void FixupCustomers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Customer item in e.NewItems)
                {
                    item.InfoSource = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Customer item in e.OldItems)
                {
                    if (ReferenceEquals(item.InfoSource, this))
                    {
                        item.InfoSource = null;
                    }
                }
            }
        }
    
        private void FixupStudents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Student item in e.NewItems)
                {
                    item.InfoSourceSmall = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Student item in e.OldItems)
                {
                    if (ReferenceEquals(item.InfoSourceSmall, this))
                    {
                        item.InfoSourceSmall = null;
                    }
                }
            }
        }

        #endregion

    }
}
