//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class StudentChangeClazzLog
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int StudentId
        {
            get { return _studentId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_studentId != value)
                    {
                        if (Student != null && Student.Id != value)
                        {
                            Student = null;
                        }
                        _studentId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _studentId;
    
        public virtual Nullable<int> OldClazzId
        {
            get { return _oldClazzId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_oldClazzId != value)
                    {
                        if (OldClazz != null && OldClazz.Id != value)
                        {
                            OldClazz = null;
                        }
                        _oldClazzId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _oldClazzId;
    
        public virtual int NewClazzId
        {
            get { return _newClazzId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_newClazzId != value)
                    {
                        if (NewClazz != null && NewClazz.Id != value)
                        {
                            NewClazz = null;
                        }
                        _newClazzId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _newClazzId;
    
        public virtual System.DateTime ChangeTime
        {
            get;
            set;
        }
    
        public virtual string OperatorName
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Clazz OldClazz
        {
            get { return _oldClazz; }
            set
            {
                if (!ReferenceEquals(_oldClazz, value))
                {
                    var previousValue = _oldClazz;
                    _oldClazz = value;
                    FixupOldClazz(previousValue);
                }
            }
        }
        private Clazz _oldClazz;
    
        public virtual Clazz NewClazz
        {
            get { return _newClazz; }
            set
            {
                if (!ReferenceEquals(_newClazz, value))
                {
                    var previousValue = _newClazz;
                    _newClazz = value;
                    FixupNewClazz(previousValue);
                }
            }
        }
        private Clazz _newClazz;
    
        public virtual Student Student
        {
            get { return _student; }
            set
            {
                if (!ReferenceEquals(_student, value))
                {
                    var previousValue = _student;
                    _student = value;
                    FixupStudent(previousValue);
                }
            }
        }
        private Student _student;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupOldClazz(Clazz previousValue)
        {
            if (previousValue != null && previousValue.Student_ChangeClazzLog.Contains(this))
            {
                previousValue.Student_ChangeClazzLog.Remove(this);
            }
    
            if (OldClazz != null)
            {
                if (!OldClazz.Student_ChangeClazzLog.Contains(this))
                {
                    OldClazz.Student_ChangeClazzLog.Add(this);
                }
                if (OldClazzId != OldClazz.Id)
                {
                    OldClazzId = OldClazz.Id;
                }
            }
            else if (!_settingFK)
            {
                OldClazzId = null;
            }
        }
    
        private void FixupNewClazz(Clazz previousValue)
        {
            if (previousValue != null && previousValue.Student_ChangeClazzLog1.Contains(this))
            {
                previousValue.Student_ChangeClazzLog1.Remove(this);
            }
    
            if (NewClazz != null)
            {
                if (!NewClazz.Student_ChangeClazzLog1.Contains(this))
                {
                    NewClazz.Student_ChangeClazzLog1.Add(this);
                }
                if (NewClazzId != NewClazz.Id)
                {
                    NewClazzId = NewClazz.Id;
                }
            }
        }
    
        private void FixupStudent(Student previousValue)
        {
            if (previousValue != null && previousValue.ChangeClazzLogs.Contains(this))
            {
                previousValue.ChangeClazzLogs.Remove(this);
            }
    
            if (Student != null)
            {
                if (!Student.ChangeClazzLogs.Contains(this))
                {
                    Student.ChangeClazzLogs.Add(this);
                }
                if (StudentId != Student.Id)
                {
                    StudentId = Student.Id;
                }
            }
        }

        #endregion

    }
}
