//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class TelSaleLog
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int CustomerId
        {
            get { return _customerId; }
            set
            {
                if (_customerId != value)
                {
                    if (Customer != null && Customer.Id != value)
                    {
                        Customer = null;
                    }
                    _customerId = value;
                }
            }
        }
        private int _customerId;
    
        public virtual string Content
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> NextTelTime
        {
            get;
            set;
        }
    
        public virtual int SalesmanId
        {
            get { return _salesmanId; }
            set
            {
                if (_salesmanId != value)
                {
                    if (Salesman != null && Salesman.Id != value)
                    {
                        Salesman = null;
                    }
                    _salesmanId = value;
                }
            }
        }
        private int _salesmanId;
    
        public virtual System.DateTime TelTime
        {
            get;
            set;
        }
    
        public virtual bool IsConvert
        {
            get;
            set;
        }
    
        public virtual bool IsSignUp
        {
            get;
            set;
        }
    
        public virtual string ConsultType
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Customer Customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    FixupCustomer(previousValue);
                }
            }
        }
        private Customer _customer;
    
        public virtual User Salesman
        {
            get { return _salesman; }
            set
            {
                if (!ReferenceEquals(_salesman, value))
                {
                    var previousValue = _salesman;
                    _salesman = value;
                    FixupSalesman(previousValue);
                }
            }
        }
        private User _salesman;

        #endregion

        #region Association Fixup
    
        private void FixupCustomer(Customer previousValue)
        {
            if (previousValue != null && previousValue.TelSaleLogs.Contains(this))
            {
                previousValue.TelSaleLogs.Remove(this);
            }
    
            if (Customer != null)
            {
                if (!Customer.TelSaleLogs.Contains(this))
                {
                    Customer.TelSaleLogs.Add(this);
                }
                if (CustomerId != Customer.Id)
                {
                    CustomerId = Customer.Id;
                }
            }
        }
    
        private void FixupSalesman(User previousValue)
        {
            if (previousValue != null && previousValue.Marketing_TelSaleLog.Contains(this))
            {
                previousValue.Marketing_TelSaleLog.Remove(this);
            }
    
            if (Salesman != null)
            {
                if (!Salesman.Marketing_TelSaleLog.Contains(this))
                {
                    Salesman.Marketing_TelSaleLog.Add(this);
                }
                if (SalesmanId != Salesman.Id)
                {
                    SalesmanId = Salesman.Id;
                }
            }
        }

        #endregion

    }
}
