//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class UserInGroup
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int UserGroupId
        {
            get { return _userGroupId; }
            set
            {
                if (_userGroupId != value)
                {
                    if (UserGroup != null && UserGroup.Id != value)
                    {
                        UserGroup = null;
                    }
                    _userGroupId = value;
                }
            }
        }
        private int _userGroupId;
    
        public virtual int UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.Id != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }
        private int _userId;

        #endregion

        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
    
        public virtual UserGroup UserGroup
        {
            get { return _userGroup; }
            set
            {
                if (!ReferenceEquals(_userGroup, value))
                {
                    var previousValue = _userGroup;
                    _userGroup = value;
                    FixupUserGroup(previousValue);
                }
            }
        }
        private UserGroup _userGroup;

        #endregion

        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.UserGroups.Contains(this))
            {
                previousValue.UserGroups.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserGroups.Contains(this))
                {
                    User.UserGroups.Add(this);
                }
                if (UserId != User.Id)
                {
                    UserId = User.Id;
                }
            }
        }
    
        private void FixupUserGroup(UserGroup previousValue)
        {
            if (previousValue != null && previousValue.Users.Contains(this))
            {
                previousValue.Users.Remove(this);
            }
    
            if (UserGroup != null)
            {
                if (!UserGroup.Users.Contains(this))
                {
                    UserGroup.Users.Add(this);
                }
                if (UserGroupId != UserGroup.Id)
                {
                    UserGroupId = UserGroup.Id;
                }
            }
        }

        #endregion

    }
}
