//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Cn.Com.Sve.OA.Entities
{
    public partial class UserGroupModulePermission
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int UserGroupId
        {
            get { return _userGroupId; }
            set
            {
                if (_userGroupId != value)
                {
                    if (UserGroup != null && UserGroup.Id != value)
                    {
                        UserGroup = null;
                    }
                    _userGroupId = value;
                }
            }
        }
        private int _userGroupId;
    
        public virtual int ModuleId
        {
            get { return _moduleId; }
            set
            {
                if (_moduleId != value)
                {
                    if (Module != null && Module.Id != value)
                    {
                        Module = null;
                    }
                    _moduleId = value;
                }
            }
        }
        private int _moduleId;

        #endregion

        #region Navigation Properties
    
        public virtual Module Module
        {
            get { return _module; }
            set
            {
                if (!ReferenceEquals(_module, value))
                {
                    var previousValue = _module;
                    _module = value;
                    FixupModule(previousValue);
                }
            }
        }
        private Module _module;
    
        public virtual UserGroup UserGroup
        {
            get { return _userGroup; }
            set
            {
                if (!ReferenceEquals(_userGroup, value))
                {
                    var previousValue = _userGroup;
                    _userGroup = value;
                    FixupUserGroup(previousValue);
                }
            }
        }
        private UserGroup _userGroup;

        #endregion

        #region Association Fixup
    
        private void FixupModule(Module previousValue)
        {
            if (previousValue != null && previousValue.UserGroupModulePermissions.Contains(this))
            {
                previousValue.UserGroupModulePermissions.Remove(this);
            }
    
            if (Module != null)
            {
                if (!Module.UserGroupModulePermissions.Contains(this))
                {
                    Module.UserGroupModulePermissions.Add(this);
                }
                if (ModuleId != Module.Id)
                {
                    ModuleId = Module.Id;
                }
            }
        }
    
        private void FixupUserGroup(UserGroup previousValue)
        {
            if (previousValue != null && previousValue.ModulePermissions.Contains(this))
            {
                previousValue.ModulePermissions.Remove(this);
            }
    
            if (UserGroup != null)
            {
                if (!UserGroup.ModulePermissions.Contains(this))
                {
                    UserGroup.ModulePermissions.Add(this);
                }
                if (UserGroupId != UserGroup.Id)
                {
                    UserGroupId = UserGroup.Id;
                }
            }
        }

        #endregion

    }
}
